[package]
name = "client"
version = "0.1.0"
edition = "2021"
authors = ["Etienne Collin <contact@etiennecollin.com>", "Emeric Laberge <emeric.laberge@umontreal.ca>"]

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
