[package]
name = "utils"
version = "0.1.0"
edition = "2021"
authors = ["Etienne Collin <contact@etiennecollin.com>", "Emeric Laberge <emeric.laberge@umontreal.ca>"]

[dependencies]
log = "0.4.22"
tokio = { version = "1.41.1", features = ["io-util", "net", "rt", "sync", "time"] }
